Update appman
Option "-H" now supports multiple arguments.

diff --git a/appman b/appman
--- a/appman
+++ b/appman
@@ -342,24 +342,45 @@ case "$1" in
   	echo " STANDALONE PROGRAMS MANAGED BY APPMAN:"); echo "";
   	cd ~/$APPSPATH && find -name 'remove' -printf "%h\n" | sort -u | echo $(xargs -n 1 basename 2> /dev/null) | du -sh * | awk '{ print " ◆ "$2 " - " $1"iB of disk space used"}'; echo "" ;;
   '-H'|'--home')
-    	if test -f ~/$APPSPATH/$2/*-bin; then
-    		echo ' ERROR: "'$2'" is NOT an AppImage'
-    	else
-    		cd ~/$APPSPATH/$2
-    		./$2 --appimage-extract AppRun > /dev/null 2>&1
-    		if test -f ~/$APPSPATH/$2/squashfs-root/AppRun; then
-    			mkdir -p ~/$APPSPATH/$2/$2.home
-    			echo ' Setting $HOME to ~/'$APPSPATH'/'$2'/'$2'.home for this AppImage'
-    			rm -R -f ~/$APPSPATH/$2/squashfs-root
-		elif test -h ~/$APPSPATH/$2/squashfs-root/AppRun; then
-    			mkdir -p ~/$APPSPATH/$2/$2.home
-    			echo ' Setting $HOME to ~/'$APPSPATH'/'$2'/'$2'.home for this AppImage'
-    			rm -R -f ~/$APPSPATH/$2/squashfs-root
+    	if [ -n "$SUDO_COMMAND" ]; then echo -e "\n WARNING: You don't need to run the option '$1' with SUDO.\n"; exit; fi
+    	while [ -n "$1" ]
+	do
+	rm -f ~/$APPSPATH/appman/.cache/home-args
+	echo $@ | tr ' ' '\n' >> ~/$APPSPATH/appman/.cache/home-args && echo STOP >> ~/$APPSPATH/appman/.cache/home-args
+	ARGS=$(sed '1d' ~/$APPSPATH/appman/.cache/home-args)
+	for arg in $ARGS; do
+	for var in $arg; do
+	if [ $arg == STOP ]; then
+		exit
+	else
+	cd ~/$APPSPATH
+	if ! test -d ./$arg; then
+		echo ' ERROR: "'$arg'" is not installed'
+	else
+	case $arg in
+    	*) keyword=$(grep -hios appimage ./$arg/AM-updater ./$arg/version | tail -1 | tr A-Z a-z 2> /dev/null)
+    	if [ "$keyword" = "appimage" ]; then
+  		cd ./$arg
+    		./$arg --appimage-extract AppRun > /dev/null 2>&1
+    		if test -f ./squashfs-root/AppRun; then
+    			mkdir -p ./$arg.home
+    			echo ' Setting $HOME to ~/'$APPSPATH'/'$arg'/'$arg'.home for this AppImage'
+    			rm -R -f ./squashfs-root; break
+    		elif test -h ./squashfs-root/AppRun; then
+    			mkdir -p ./$arg.home
+    			echo ' Setting $HOME to ~/'$APPSPATH'/'$arg'/'$arg'.home for this AppImage'
+    			rm -R -f ./squashfs-root; break
     		else
-    			echo ' ERROR: "'$2'" is NOT an AppImage'
+    			echo ' ERROR: "'$arg'" is NOT an AppImage'; break
     		fi
-    		
-    	fi;;
+    		else echo ' ERROR: "'$arg'" is NOT an AppImage'; break
+    	fi
+    	esac
+    	fi
+    	fi
+    	done
+    	done
+    	done;;
   '-i'|'install')
 	while [ -n "$1" ]
 	do
@@ -1150,5 +1171,5 @@ case "$1" in
 	done
 	shift;;
   'version'|'-v'|'--version')
-  	echo "4.2.2-5";;
+  	echo "4.2.2-6";;
 esac
