Changed dependency commands to POSIX compliance.
https://github.com/ivan-hc/AM-Application-Manager/pull/32

diff --git a/appman b/appman
--- a/appman
+++ b/appman
@@ -18,11 +18,10 @@ APPSPATH=$(cat ~/.config/appman/appman-config)
 mkdir -p ~/.local/bin ~/.local/share/applications ~/.local/share/icons ~/$APPSPATH/appman ~/$APPSPATH/appman/.cache
 cd ~/$APPSPATH/appman
 
-for name in "ar" "cat" "chmod" "chown" "curl" "echo" "egrep" "grep" "sed" "tar" "test" "unzip" "wget" "zsync"
-do
-  [[ $(which $name 2>/dev/null) ]] || { echo "" && echo -e 'ERROR: "'$name'" not found, required by some installation scripts.';deps=1; }
-done
-[[ $deps -ne 1 ]] || { echo -e "\nInstall the above and try again\n";exit 1; }
+for name in "ar" "cat" "chmod" "chown" "curl" "grep" "sed" "tar" "unzip" "wget" "zsync"; do
+  test -x "$(command -v $name 2>/dev/null)" \
+  || { printf "\n%s\n" "ERROR: $name not found, required by some installation scripts."; deps=1; };
+done; [ "$deps" != "1" ] || { printf "\nInstall the above and try again\n\n"; exit 1; }
 
 AMREPO="https://raw.githubusercontent.com/ivan-hc/AM-application-manager/main"
 arch=$(printf '%s\n' "$HOSTTYPE")
